User.create(username: "guest", password: "password", email:"guest@guest.com")
User.create(username: "tyler", password: "password", email:"tyler@tylerfields.net")
User.create(username: "rhonda", password: "password", email:"rhonda@example.com")
User.create(username: "tom", password: "password", email:"tom@example.com")
User.create(username: "austin", password: "password", email:"austin@example.com")
User.create(username: "levi", password: "password", email:"levi@example.com")
User.create(username: "caleb", password: "password", email:"caleb@example.com")
User.create(username: "ashley", password: "password", email:"ashley@example.com")
User.create(username: "shirley", password: "password", email:"shirley@example.com")
User.create(username: "dan", password: "password", email:"dan@example.com")
User.create(username: "kris", password: "password", email:"kris@example.com")
User.create(username: "ryan", password: "password", email:"ryan@example.com")
User.create(username: "seth", password: "password", email:"seth@example.com")
User.create(username: "justin", password: "password", email:"justin@example.com")
User.create(username: "eli", password: "password", email:"eli@example.com")

List.create(name: "Family Groceries")
List.create(name: "Vegan Pancakes")
List.create(name: "Party Supplies")
List.create(name: "Road Trip!")

UserListAssociation.create(list_id:1, user_id:1)
UserListAssociation.create(list_id:1, user_id:2)
UserListAssociation.create(list_id:1, user_id:3)
UserListAssociation.create(list_id:1, user_id:4)
UserListAssociation.create(list_id:1, user_id:8)
UserListAssociation.create(list_id:1, user_id:9)
UserListAssociation.create(list_id:1, user_id:12)
UserListAssociation.create(list_id:1, user_id:13)
UserListAssociation.create(list_id:1, user_id:14)
UserListAssociation.create(list_id:2, user_id:1)
UserListAssociation.create(list_id:2, user_id:2)
UserListAssociation.create(list_id:2, user_id:8)
UserListAssociation.create(list_id:3, user_id:1)
UserListAssociation.create(list_id:3, user_id:2)
UserListAssociation.create(list_id:3, user_id:6)
UserListAssociation.create(list_id:3, user_id:8)
UserListAssociation.create(list_id:3, user_id:10)
UserListAssociation.create(list_id:3, user_id:11)
UserListAssociation.create(list_id:4, user_id:1)
UserListAssociation.create(list_id:4, user_id:2)
UserListAssociation.create(list_id:4, user_id:5)
UserListAssociation.create(list_id:4, user_id:15)

ListItem.create(name: "Almond Milk", list_id: 1, purchased: false, quantity: 1, user_id: nil)
ListItem.create(name: "Coffee Beans", list_id: 1, purchased: true, quantity: 1, user_id: 2)
ListItem.create(name: "Mushrooms", list_id: 1, purchased: false, quantity: 3, user_id: 4)
ListItem.create(name: "Apples", list_id: 1, purchased: false, quantity: 12, user_id: nil)
ListItem.create(name: "Cherry Tomatoes", list_id: 1, purchased: false, quantity: 20, user_id: nil)
ListItem.create(name: "Veggie Burgers", list_id: 1, purchased: false, quantity: 9, user_id: 8)
ListItem.create(name: "Buns", list_id: 1, purchased: true, quantity: 9, user_id: nil)
ListItem.create(name: "Flour", list_id: 2, purchased: false, quantity: 1, user_id: 1)
ListItem.create(name: "Brown Sugar", list_id: 2, purchased: false, quantity: 1, user_id: nil)
ListItem.create(name: "Baking Soda", list_id: 2, purchased: true, quantity: 1, user_id: nil)
ListItem.create(name: "Salt", list_id: 2, purchased: false, quantity: 1, user_id: 8)
ListItem.create(name: "Banana", list_id: 2, purchased: false, quantity: 2, user_id: 2)
ListItem.create(name: "Cooking Spray", list_id: 2, purchased: true, quantity: 1, user_id: nil)
ListItem.create(name: "Chips", list_id: 3, purchased: true, quantity: 2, user_id: nil)
ListItem.create(name: "Salsa", list_id: 3, purchased: true, quantity: 1, user_id: 1)
ListItem.create(name: "Guacamole", list_id: 3, purchased: false, quantity: 1, user_id: 1)
ListItem.create(name: "Soda", list_id: 3, purchased: false, quantity: 6, user_id: 6)
ListItem.create(name: "Vegan Ice Cream", list_id: 3, purchased: false, quantity: 4, user_id: nil)
ListItem.create(name: "Chips", list_id: 4, purchased: false, quantity: 4, user_id: 1)
ListItem.create(name: "Bottled Water", list_id: 4, purchased: false, quantity: 4, user_id: 2)
ListItem.create(name: "Granola Bars", list_id: 4, purchased: true, quantity: 4, user_id: nil)
ListItem.create(name: "Gatorade", list_id: 4, purchased: true, quantity: 10, user_id: nil)
ListItem.create(name: "Trail Mix", list_id: 4, purchased: false, quantity: 4, user_id: 5)
ListItem.create(name: "Cashews", list_id: 4, purchased: false, quantity: 1, user_id: 15)

Comment.create(content:"Does this seem like everything we need?", list_id:1, user_id:1, list_item_id: nil)
Comment.create(content:"Yeah!", list_id:1, user_id:8, list_item_id: nil)
Comment.create(content:"What kind of coffee did you get?", list_id:1, user_id:13, list_item_id: 2)
Comment.create(content:"Peet's Major Dickason's Blend", list_id:1, user_id:2, list_item_id: 2)
Comment.create(content:"Awesome! That's my favorite!", list_id:1, user_id:4, list_item_id: 2)
Comment.create(content:"I got buns.", list_id:1, user_id:9, list_item_id: 7)
Comment.create(content:"Great!", list_id:1, user_id:3, list_item_id: nil)
Comment.create(content:"This recipe is so good!", list_id:2, user_id:8, list_item_id: nil)
Comment.create(content:"We already have baking soda.", list_id:2, user_id:1, list_item_id: 10)
Comment.create(content:"Oh! We have Cooking Spray too!", list_id:2, user_id:1, list_item_id: 13)
Comment.create(content:"I agree Ashley, this recipe is Awesome!", list_id:2, user_id:1, list_item_id: nil)
Comment.create(content:"I'm stoked for this party!", list_id:3, user_id:10, list_item_id: nil)
Comment.create(content:"Do we need to add red cups to the list?", list_id:3, user_id:1, list_item_id: nil)
Comment.create(content:"No we have some already.", list_id:3, user_id:6, list_item_id: nil)
Comment.create(content:"What kind of ice cream do we want?", list_id:3, user_id:11, list_item_id: 18)
Comment.create(content:"Same goes for soda.", list_id:3, user_id:6, list_item_id: 17)
Comment.create(content:"I really like the Ben and Jerry's dairy free Coffee one.", list_id:3, user_id:2, list_item_id: 18)
Comment.create(content:"And I'm a fan of Dr. Pepper!", list_id:3, user_id:2, list_item_id: 17)
Comment.create(content:"Have we figured out where we're headed yet?", list_id:4, user_id:15, list_item_id: nil)
Comment.create(content:"Nope! That's the exciting thing about a road trip! The trip is the destination!", list_id:4, user_id:2, list_item_id: nil)
Comment.create(content:"Do you guys have any preferance on water brand?", list_id:4, user_id:2, list_item_id: 20)
Comment.create(content:"Who care's about the brand of water? Isn't it all the same?", list_id:4, user_id:5, list_item_id: 20)
Comment.create(content:"You'd think so, but my wife cares about it. So I thought I'd just check!", list_id:4, user_id:2, list_item_id: 20)
Comment.create(content:"We need to get started on the playlist!", list_id:4, user_id:1, list_item_id: nil)
